# Generated by Django 4.1 on 2024-07-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingpermit",
            name="application_number",
            field=models.CharField(
                default="ebdabae8-abc6-43d1-a26c-98b5a763a358", max_length=50
            ),
        ),
    ]
