# Generated by Django 4.1 on 2024-07-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingpermit",
            name="application_number",
            field=models.CharField(
                default="c9c6bd48-fe64-4401-bd71-e23ccb05be3b", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="buildingpermit",
            name="date",
            field=models.CharField(default="July 25, 2024", max_length=50),
        ),
    ]
