# Generated by Django 5.0.6 on 2024-07-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='151627df-5c2f-435f-94ef-a43efbb6caac', max_length=50),
        ),
    ]
