# Generated by Django 5.0.6 on 2024-07-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='c98589ab-29a3-4357-9819-d9ccbf6eb045', max_length=50),
        ),
    ]
