# Generated by Django 5.0.6 on 2024-07-26 02:13

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='additional_document_1',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.user_land_records_path),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='additional_document_2',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.user_land_records_path),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='additional_document_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='76a8c316-67f3-41b4-be8a-026160a9b5b6', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('additional', 'Additional Document Required')], default='submitted', max_length=20),
        ),
    ]
