# Generated by Django 5.0.6 on 2024-07-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='3051f1ac-6552-44b4-9ebb-562f90db3f14', max_length=50),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
