# Generated by Django 5.0.6 on 2024-07-25 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='user_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='0d655433-1707-4b31-98a9-993611d5130e', max_length=50),
        ),
    ]
