# Generated by Django 5.0.6 on 2024-07-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='buildingpermit',
            name='application_status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in progress', 'In Progress'), ('approved', 'Approved')], default='submitted', max_length=20),
        ),
    ]
