# Generated by Django 4.1 on 2024-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_buildingpermit_application_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingpermit",
            name="application_number",
            field=models.CharField(
                default="ac952f56-6c47-4872-9ed5-6e45b2790c20", max_length=50
            ),
        ),
    ]
