# Generated by Django 5.0.6 on 2024-07-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='7385374a-1fb0-4caf-bae0-3ef34114d613', max_length=50),
        ),
    ]
