# Generated by Django 5.0.6 on 2024-07-25 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buildingpermit_user_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='ad3dceb1-cbf3-4afb-afee-aaf2c9c20ef6', max_length=50),
        ),
    ]
