# Generated by Django 5.0.6 on 2024-07-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_buildingpermit_additional_document_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='3bd33ea1-b120-42e7-8ed8-b630b22e857e', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 26, 2024', max_length=50),
        ),
    ]
