# Generated by Django 5.0.6 on 2024-07-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='visit_count',
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='dfb9d9c0-37ae-43cd-8b9f-98f221854755', max_length=50),
        ),
    ]
