# Generated by Django 5.0.6 on 2024-07-26 13:05

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='additional_document_1',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.user_additional_document_1_path),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='additional_document_2',
            field=models.FileField(blank=True, null=True, upload_to=myapp.models.user_additional_records_2_path),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='8d181b5e-fcce-4d19-97a5-2b2f69214487', max_length=50),
        ),
    ]
