# Generated by Django 5.0.6 on 2024-07-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buildingpermit_application_number'),
        ('myapp', '0003_delete_adminuser'),
    ]

    operations = [
    ]
