# Generated by Django 5.0.6 on 2024-07-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buildingpermit',
            old_name='user_model',
            new_name='usr',
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='ed7d9f51-ef48-4815-a132-bfbbcdc6441b', max_length=50),
        ),
    ]
