# Generated by Django 5.0.6 on 2024-07-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_merge_20240719_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 19, 2024', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='6bb22672-9471-410c-82b3-fad20a3bd1e5', max_length=50),
        ),
    ]
