# Generated by Django 5.0.6 on 2024-07-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='1f674101-c5b0-40c4-b293-105997ed4ce8', max_length=50),
        ),
    ]
