# Generated by Django 5.0.6 on 2024-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='d2230fb8-cabc-4ec7-80c7-645bae99aa72', max_length=50),
        ),
    ]
