# Generated by Django 5.0.6 on 2024-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='1a58d453-75d3-4614-ae1a-4741813677f7', max_length=50),
        ),
    ]
