# Generated by Django 5.0.6 on 2024-07-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingpermit',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='5a7a911c-9f7a-4084-a144-c45dc0708244', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 20, 2024', max_length=50),
        ),
    ]
