# Generated by Django 5.0.6 on 2024-07-20 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_buildingpermit_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='413bf94f-2661-4cd3-8f0e-c0973e4862d2', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
