# Generated by Django 5.0.6 on 2024-07-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='07cf0bf1-c9b9-40c0-9f7a-cead77a246ee', max_length=50),
        ),
    ]
