# Generated by Django 5.0.6 on 2024-07-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0012_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='4c686799-4200-433a-b292-951dca131c24', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 21, 2024', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
