# Generated by Django 5.0.6 on 2024-07-21 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_buildingpermit_application_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='09f80010-2b7b-45ef-ba3c-7bd57d70270f', max_length=50),
        ),
    ]
