# Generated by Django 5.0.6 on 2024-07-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='161af8fa-c8ad-4130-a19f-3d2c2c710911', max_length=50),
        ),
    ]
