# Generated by Django 5.0.6 on 2024-07-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='78c13eeb-fe6a-4222-a4a1-15deaec0c2e1', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 22, 2024', max_length=50),
        ),
    ]
