# Generated by Django 5.0.6 on 2024-07-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_buildingpermit_application_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='c74ff314-38de-43e7-84d2-39034bec0ca7', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 22, 2024', max_length=50),
        ),
    ]
