# Generated by Django 5.0.6 on 2024-07-24 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_contactmodel_alter_buildingpermit_application_number_and_more'),
        ('myapp', '0016_contactmodel_customuser_is_admin_and_more'),
    ]

    operations = [
    ]
