# Generated by Django 5.0.6 on 2024-07-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myapp', '0017_merge_20240724_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='056f7b98-9a4f-4354-8f33-ae7822f93664', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 24, 2024', max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='CustomUser_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='CustomUser_permissions_set', to='auth.permission'),
        ),
    ]
