# Generated by Django 5.0.6 on 2024-07-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_merge_20240724_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingpermit',
            name='application_number',
            field=models.CharField(default='5a2036db-565c-4548-8624-228f32d131c8', max_length=50),
        ),
        migrations.AlterField(
            model_name='buildingpermit',
            name='date',
            field=models.CharField(default='July 24, 2024', max_length=50),
        ),
    ]
